defaults: &defaults
  adapter: postgresql
  encoding: unicode
  username: postgres
  password:
  host: localhost

development:
  <<: *defaults
  database: todos_orbit_development

test: &test
  <<: *defaults
  database: todos_orbit_test

cucumber:
  <<: *test

